language: cpp
compiler:
- gcc
os: linux
dist: trusty
sudo: required
before_install:
  - pip install --user cpp-coveralls
before_script: mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug && cd ..
script: cd build && make -j2 && make test && cd ..
after_success:
  - coveralls --include /home/travis/build/feuerloescher/aurum-lang --exclude /usr --exclude /home/travis/build/feuerloescher/aurum-lang/build --exclude /home/travis/build/feuerloescher/aurum-lang/cov-build --gcov-options '\-lp'
addons:
 coverity_scan:
   project:
    name: "feuerloescher/aurum-lang"
    description: "Build submitted via Travis CI"
   notification_email: max.mail@dameweb.de
   build_command_prepend: "mkdir cov-build && cd cov-build && cmake ../ -DCMAKE_BUILD_TYPE=Debug"
   build_command: "make -j2"
   branch_pattern: master
env:
  global:
  - LANG="en_US.UTF-8"
  - secure: "TkgLmUIyOjNj0eT0ZeECzrbV7c6Ch46Z/K53e/CKB2TdAXiPNfpW4OYWyRmflL0THitiAW3DDO0kxFzT7XQVZeuLcjc3VPI6/VsSJ5PXk0gTysfhgaszywqN4A4wRm29Gt7FAHOxyVTVb1yRKK9VHgTEGMMsEQR3noQm+ugnrN4tfy1yuaKshIOsS9PfjIbnnvlpNc7n8Y5JyAnp5w2FFomcCYPri4Q3cWfHY5Td2Q4YGOVeyVb/4axfnoXSJ10IKVINpe2eKNA3tRtNEwLVFJqO2jVNWWmhQ7y+NNV24eQ6CPND3PoRD7ewHNHe0nLGCnOZLTHjeI6Vd1yMj4/V4h04a3sj8dwlfbkGDZ/QwLE8mWfzvV6s+0YQT36Q/VuYxNkp8osC6NfV7m2whQnFjrlYbW/jZNOkyfFZBur7Ijmz3FVAhciqHbwzvwLzofdyb00meZTIOIP7MoW472e2qOOxwvzsvLoNddoqmAF24UDfDUJGYOQSBD0zOIQ0Pidf5JQUGWoxL1sh5jmQ8WPPEd0AEcVGjVZ1mb3pqPR69NL73PNuDIx6n/efucaWoz+F2kiTuf62g0yZPsHuGnGdSZPAlHWUcHnupE/oHw3zUyno9Wj5efTdgA3Wwp+hkcn68ulLAH89Ra4BJLCiFVwA1x8dNd90QePQA0Co4dc7krI="
