language: cpp
compiler:
- gcc
os: linux
dist: trusty
sudo: required
before_install:
  - wget -v -O /tmp/cov-analysis-Linux.tgz https://scan.coverity.com/download/Linux --post-data "project=feuerloescher/aurum-lang&token=$COVERITY_SCAN_TOKEN" --no-check-certificate
  - mkdir -p /tmp/coverity-scan-analysis && pushd /tmp/coverity-scan-analysis && tar xzf /tmp/cov-analysis-Linux.tgz && popd
  - gem install coveralls-lcov
  - wget http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O /tmp/llvm.tar.xz
  - pushd /tmp && tar xf /tmp/llvm.tar.xz && popd
addons:
 apt:
   packages:
   - lcov
   - ca-certificates
 coverity_scan:
   project:
    name: "feuerloescher/aurum-lang"
    description: "Build submitted via Travis CI"
   notification_email: max.mail@dameweb.de
   build_command_prepend: "mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug"
   build_command: "make -j2"
   branch_pattern: master
script: mkdir -p build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug && make -j2 && make test && cd ..
after_success:
  - cd build && make test_coverage && coveralls-lcov tests/coverage.info && cd ..
env:
  global:
  - LANG="en_US.UTF-8"
  - CTEST_OUTPUT_ON_FAILURE=1
  - secure: "TkgLmUIyOjNj0eT0ZeECzrbV7c6Ch46Z/K53e/CKB2TdAXiPNfpW4OYWyRmflL0THitiAW3DDO0kxFzT7XQVZeuLcjc3VPI6/VsSJ5PXk0gTysfhgaszywqN4A4wRm29Gt7FAHOxyVTVb1yRKK9VHgTEGMMsEQR3noQm+ugnrN4tfy1yuaKshIOsS9PfjIbnnvlpNc7n8Y5JyAnp5w2FFomcCYPri4Q3cWfHY5Td2Q4YGOVeyVb/4axfnoXSJ10IKVINpe2eKNA3tRtNEwLVFJqO2jVNWWmhQ7y+NNV24eQ6CPND3PoRD7ewHNHe0nLGCnOZLTHjeI6Vd1yMj4/V4h04a3sj8dwlfbkGDZ/QwLE8mWfzvV6s+0YQT36Q/VuYxNkp8osC6NfV7m2whQnFjrlYbW/jZNOkyfFZBur7Ijmz3FVAhciqHbwzvwLzofdyb00meZTIOIP7MoW472e2qOOxwvzsvLoNddoqmAF24UDfDUJGYOQSBD0zOIQ0Pidf5JQUGWoxL1sh5jmQ8WPPEd0AEcVGjVZ1mb3pqPR69NL73PNuDIx6n/efucaWoz+F2kiTuf62g0yZPsHuGnGdSZPAlHWUcHnupE/oHw3zUyno9Wj5efTdgA3Wwp+hkcn68ulLAH89Ra4BJLCiFVwA1x8dNd90QePQA0Co4dc7krI="
