AUC: AST::ASTElement Class Reference
AST::ASTElement Class Reference abstract
#include <ASTElement.hpp>
Public Member Functions
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
virtual void runPass (ASTPass &pass)=0
CodeLocation getCodeLocation ()
Protected Attributes
CodeLocation codeLocation
Detailed Description
Definition at line 15 of file ASTElement.hpp.
Constructor & Destructor Documentation
ASTElement()
ASTElement::ASTElement (CodeLocation codeLocation) explicit
Definition at line 11 of file ASTElement.cpp.
~ASTElement()
virtual AST::ASTElement::~ASTElement () inline virtual
Definition at line 22 of file ASTElement.hpp.
References getCodeLocation(), and runPass().
Member Function Documentation
getCodeLocation()
CodeLocation ASTElement::getCodeLocation ()
Definition at line 15 of file ASTElement.cpp.
References codeLocation.
Referenced by AST::ASTPass::handleError(), Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and ~ASTElement().
runPass()
virtual void AST::ASTElement::runPass (ASTPass & pass) pure virtual
Implemented in AST::VariableExpr, AST::ConstIntExpr, AST::VariableDefAssignStmt, AST::WhileLoop, AST::FunctionDef, AST::VariableDefStmt, AST::IfStmt, AST::BasicTypeStmt, AST::FunctionCallExpr, AST::FunctionDecl, AST::ReturnStmt, AST::Block, AST::Expression, and AST::Statement.
Referenced by ~ASTElement(), AST::BasicTypeStmt::~BasicTypeStmt(), AST::FunctionDecl::~FunctionDecl(), and AST::FunctionDef::~FunctionDef().
Member Data Documentation
codeLocation
CodeLocation AST::ASTElement::codeLocation protected
Definition at line 18 of file ASTElement.hpp.
Referenced by getCodeLocation().
The documentation for this class was generated from the following files:
auc/AST/ASTElement.hpp
auc/AST/ASTElement.cpp