AUC: AST::Statement Class Reference
AST::Statement Class Reference abstract
#include <Statements.hpp>
Public Member Functions
Statement (CodeLocation codeLocation)
virtual ~Statement ()
virtual void runPass (ASTPass &pass)=0
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Additional Inherited Members
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 18 of file Statements.hpp.
Constructor & Destructor Documentation
Statement()
Statement::Statement (CodeLocation codeLocation)
Definition at line 12 of file Statements.cpp.
~Statement()
virtual AST::Statement::~Statement () inline virtual
Definition at line 22 of file Statements.hpp.
References runPass().
Member Function Documentation
runPass()
virtual void AST::Statement::runPass (ASTPass & pass) pure virtual
Implements AST::ASTElement.
Implemented in AST::VariableExpr, AST::ConstIntExpr, AST::VariableDefAssignStmt, AST::WhileLoop, AST::VariableDefStmt, AST::IfStmt, AST::FunctionCallExpr, AST::ReturnStmt, AST::Block, and AST::Expression.
Referenced by AST::ReturnStmt::~ReturnStmt(), ~Statement(), AST::VariableDefAssignStmt::~VariableDefAssignStmt(), and AST::VariableDefStmt::~VariableDefStmt().
The documentation for this class was generated from the following files:
auc/AST/Statements.hpp
auc/AST/Statements.cpp