AUC: AST::VariableDefStmt Class Reference
AST::VariableDefStmt Class Reference
#include <Statements.hpp>
Public Member Functions
VariableDefStmt (ASTPtr< TypeStmt > typeStmt, std::string name, Block *parentBlock, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)
std::string getName ()
ASTPtr< TypeStmt > getTypeStmt ()
llvm::AllocaInst * getAllocaInst ()
void setAllocaInst (llvm::AllocaInst *allocaInst)
Public Member Functions inherited from AST::Statement
Statement (Block *parentBlock, CodeLocation codeLocation)
Block * getParentBlock ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
ASTPtr< TypeStmt > typeStmt
std::string name
llvm::AllocaInst * allocaInst
Protected Attributes inherited from AST::Statement
Block * parentBlock
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 48 of file Statements.hpp.
Constructor & Destructor Documentation
VariableDefStmt::VariableDefStmt (ASTPtr< TypeStmt > typeStmt, std::string name, Block * parentBlock, CodeLocation codeLocation)
Definition at line 35 of file Statements.cpp.
Member Function Documentation
llvm::AllocaInst * VariableDefStmt::getAllocaInst ()
Definition at line 53 of file Statements.cpp.
References allocaInst.
Referenced by Passes::LLVMPass::runOn().
std::string VariableDefStmt::getName ()
Definition at line 45 of file Statements.cpp.
References name.
Referenced by Passes::IdentifierPass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
ASTPtr< TypeStmt > VariableDefStmt::getTypeStmt ()
Definition at line 49 of file Statements.cpp.
References typeStmt.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
void VariableDefStmt::runPass (ASTPass & pass) virtual
Implements AST::ASTElement.
Reimplemented in AST::VariableDefAssignStmt.
Definition at line 41 of file Statements.cpp.
References AST::ASTPass::runOn().
void VariableDefStmt::setAllocaInst (llvm::AllocaInst * allocaInst)
Definition at line 57 of file Statements.cpp.
References allocaInst.
Referenced by Passes::LLVMPass::runOn().
Member Data Documentation
llvm::AllocaInst* AST::VariableDefStmt::allocaInst protected
Definition at line 53 of file Statements.hpp.
Referenced by getAllocaInst(), and setAllocaInst().
std::string AST::VariableDefStmt::name protected
Definition at line 52 of file Statements.hpp.
Referenced by getName().
ASTPtr<TypeStmt> AST::VariableDefStmt::typeStmt protected
Definition at line 51 of file Statements.hpp.
Referenced by getTypeStmt().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Statements.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Statements.cpp