AUC: Passes::StdLibPass Class Reference
Passes::StdLibPass Class Reference
Register builtin types and functions of the language.
#include <StdLibPass.hpp>
Public Member Functions
StdLibPass (AST::AbstractSyntaxTree &ast)
virtual ~StdLibPass ()
void run ()
Protected Member Functions
void addScalarTypes ()
Protected Attributes
AST::AbstractSyntaxTree & ast
AST::ASTMap< type::TypePtr > & types
Detailed Description
Register builtin types and functions of the language.
Definition at line 17 of file StdLibPass.hpp.
Constructor & Destructor Documentation
StdLibPass()
StdLibPass::StdLibPass (AST::AbstractSyntaxTree & ast) explicit
Definition at line 16 of file StdLibPass.cpp.
~StdLibPass()
virtual Passes::StdLibPass::~StdLibPass () inline virtual
Definition at line 27 of file StdLibPass.hpp.
References run().
Member Function Documentation
addScalarTypes()
void StdLibPass::addScalarTypes () protected
Definition at line 25 of file StdLibPass.cpp.
References ast, AST::ASTMap< T >::find(), AST::AbstractSyntaxTree::getStdLibFunctionDecls(), AST::ASTMap< T >::insert(), and types.
Referenced by run().
run()
void StdLibPass::run ()
more to come...
Definition at line 20 of file StdLibPass.cpp.
References addScalarTypes().
Referenced by ~StdLibPass().
Member Data Documentation
ast
AST::AbstractSyntaxTree& Passes::StdLibPass::ast protected
Definition at line 20 of file StdLibPass.hpp.
Referenced by addScalarTypes().
types
AST::ASTMap<type::TypePtr>& Passes::StdLibPass::types protected
Definition at line 21 of file StdLibPass.hpp.
Referenced by addScalarTypes().
The documentation for this class was generated from the following files:
auc/Passes/StdLibPass.hpp
auc/Passes/StdLibPass.cpp