AUC: AST::FunctionDef Class Reference
AST::FunctionDef Class Reference
#include <Declarations.hpp>
Public Member Functions
FunctionDef (FunctionDeclPtr funcDecl, BlockPtr body, CodeLocation codeLocation)
virtual ~FunctionDef ()
virtual void runPass (ASTPass &pass)
std::string getName ()
FunctionDeclPtr getFunctionDecl ()
BlockPtr getBody ()
Public Member Functions inherited from AST::Declaration
Declaration (bool exported, CodeLocation codeLocation)
virtual ~Declaration ()
bool getExported ()
void setExported (bool exported)
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Protected Attributes
FunctionDeclPtr funcDecl
BlockPtr body
Protected Attributes inherited from AST::Declaration
bool exported
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 51 of file Declarations.hpp.
Constructor & Destructor Documentation
FunctionDef()
FunctionDef::FunctionDef (FunctionDeclPtr funcDecl, BlockPtr body, CodeLocation codeLocation)
Definition at line 49 of file Declarations.cpp.
~FunctionDef()
virtual AST::FunctionDef::~FunctionDef () inline virtual
Definition at line 59 of file Declarations.hpp.
References AST::ASTElement::runPass().
Member Function Documentation
getBody()
BlockPtr FunctionDef::getBody ()
Definition at line 65 of file Declarations.cpp.
References body.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
getFunctionDecl()
FunctionDeclPtr FunctionDef::getFunctionDecl ()
Definition at line 61 of file Declarations.cpp.
References funcDecl.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
getName()
std::string FunctionDef::getName ()
Definition at line 57 of file Declarations.cpp.
References funcDecl.
Referenced by Passes::OutputPass::runOn().
runPass()
void FunctionDef::runPass (ASTPass & pass) virtual
Implements AST::ASTElement.
Definition at line 53 of file Declarations.cpp.
References AST::ASTPass::tryRunOn().
Member Data Documentation
body
BlockPtr AST::FunctionDef::body protected
Definition at line 55 of file Declarations.hpp.
Referenced by getBody().
funcDecl
FunctionDeclPtr AST::FunctionDef::funcDecl protected
Definition at line 54 of file Declarations.hpp.
Referenced by getFunctionDecl(), and getName().
The documentation for this class was generated from the following files:
auc/AST/Declarations.hpp
auc/AST/Declarations.cpp