AUC: AST::ASTMap< T > Class Template Reference
AST::ASTMap< T > Class Template Reference
#include <ASTMap.hpp>
Public Member Functions
void clear ()
void insert (T t, CodeLocation codeLocation)
void insert (T t, std::string name, CodeLocation codeLocation)
T find (std::string name)
InternalMapType< T >::iterator begin ()
InternalMapType< T >::iterator end ()
Protected Attributes
InternalMapType< T > internalMap
Detailed Description
template<class T>
class AST::ASTMap< T >
Definition at line 24 of file ASTMap.hpp.
Member Function Documentation
begin()
template<class T > InternalMapType< T >::iterator ASTMap::begin ()
Definition at line 43 of file ASTMap.cpp.
clear()
template<class T > void ASTMap::clear ()
Definition at line 17 of file ASTMap.cpp.
end()
template<class T > InternalMapType< T >::iterator ASTMap::end ()
Definition at line 48 of file ASTMap.cpp.
find()
template<class T > T ASTMap::find (std::string name)
Definition at line 34 of file ASTMap.cpp.
Referenced by Passes::StdLibPass::addScalarTypes(), Passes::IdentifierPass::runOn(), and Passes::TypePass::runOn().
insert() [1/2]
template<class T> void ASTMap::insert (T t, CodeLocation codeLocation)
Definition at line 22 of file ASTMap.cpp.
Referenced by Passes::StdLibPass::addScalarTypes().
insert() [2/2]
template<class T> void ASTMap::insert (T t, std::string name, CodeLocation codeLocation)
Definition at line 27 of file ASTMap.cpp.
Member Data Documentation
internalMap
template<class T> InternalMapType<T> AST::ASTMap< T >::internalMap protected
Definition at line 27 of file ASTMap.hpp.
The documentation for this class was generated from the following files:
auc/AST/ASTMap.hpp
auc/AST/ASTMap.cpp