AUC: AST::Declaration Class Reference
AST::Declaration Class Reference abstract
#include <Declarations.hpp>
Public Member Functions
Declaration (ASTPtr< TypeStmt > returnTypeStmt, std::string name, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)=0
std::string getName ()
ASTPtr< TypeStmt > getReturnTypeStmt ()
VariableDefStmtList & getParameters ()
Block & getBody ()
llvm::Function * getLLVMFunction ()
void setLLVMFunction (llvm::Function *llvmFunction)
std::vector< llvm::Type * > & getParameterLLVMTypes ()
bool getExported ()
void setExported (bool exported)
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
std::string name
ASTPtr< TypeStmt > returnTypeStmt
ASTList< VariableDefStmt > parameters
Block body
llvm::Function * llvmFunction
std::vector< llvm::Type * > parameterLLVMTypes
bool exported
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 21 of file Declarations.hpp.
Constructor & Destructor Documentation
Declaration::Declaration (ASTPtr< TypeStmt > returnTypeStmt, std::string name, CodeLocation codeLocation)
Definition at line 14 of file Declarations.cpp.
Member Function Documentation
Block & Declaration::getBody ()
Definition at line 32 of file Declarations.cpp.
References body.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
bool Declaration::getExported ()
Definition at line 48 of file Declarations.cpp.
References exported.
Referenced by Passes::LLVMPass::runOn().
llvm::Function * Declaration::getLLVMFunction ()
Definition at line 36 of file Declarations.cpp.
References llvmFunction.
Referenced by Passes::VerifyOptimizePass::runOn(), and Passes::LLVMPass::runOn().
std::string Declaration::getName ()
Definition at line 20 of file Declarations.cpp.
References name.
Referenced by AST::MethodDef::MethodDef(), Passes::IdentifierPass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
std::vector< llvm::Type * > & Declaration::getParameterLLVMTypes ()
Definition at line 44 of file Declarations.cpp.
References parameterLLVMTypes.
Referenced by Passes::LLVMPass::runOn().
VariableDefStmtList & Declaration::getParameters ()
Definition at line 28 of file Declarations.cpp.
References parameters.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
ASTPtr< TypeStmt > Declaration::getReturnTypeStmt ()
Definition at line 24 of file Declarations.cpp.
References returnTypeStmt.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
virtual void AST::Declaration::runPass (ASTPass & pass) pure virtual
Implements AST::ASTElement.
Implemented in AST::MethodDef, and AST::FunctionDef.
void Declaration::setExported (bool exported)
Definition at line 52 of file Declarations.cpp.
References exported.
void Declaration::setLLVMFunction (llvm::Function * llvmFunction)
Definition at line 40 of file Declarations.cpp.
References llvmFunction.
Referenced by Passes::LLVMPass::runOn().
Member Data Documentation
Block AST::Declaration::body protected
Definition at line 27 of file Declarations.hpp.
Referenced by getBody(), and AST::MethodDef::MethodDef().
bool AST::Declaration::exported protected
Definition at line 30 of file Declarations.hpp.
Referenced by getExported(), and setExported().
llvm::Function* AST::Declaration::llvmFunction protected
Definition at line 28 of file Declarations.hpp.
Referenced by getLLVMFunction(), and setLLVMFunction().
std::string AST::Declaration::name protected
Definition at line 24 of file Declarations.hpp.
Referenced by getName(), and AST::MethodDef::MethodDef().
std::vector<llvm::Type*> AST::Declaration::parameterLLVMTypes protected
Definition at line 29 of file Declarations.hpp.
Referenced by getParameterLLVMTypes().
ASTList<VariableDefStmt> AST::Declaration::parameters protected
Definition at line 26 of file Declarations.hpp.
Referenced by getParameters(), and AST::MethodDef::MethodDef().
ASTPtr<TypeStmt> AST::Declaration::returnTypeStmt protected
Definition at line 25 of file Declarations.hpp.
Referenced by getReturnTypeStmt().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Declarations.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Declarations.cpp