AUC: Passes::IdentifierPass Class Reference
Passes::IdentifierPass Class Reference
Resolve string identifiers of variables and functions.
#include <IdentifierPass.hpp>
Public Member Functions
IdentifierPass (AST::AbstractSyntaxTree &ast)
virtual ~IdentifierPass ()
void run () override
void runOn (AST::FunctionDecl &) override
void runOn (AST::FunctionDef &) override
void runOn (AST::ReturnStmt &) override
void runOn (AST::VariableDefStmt &) override
void runOn (AST::VariableDefAssignStmt &) override
void runOn (AST::Block &) override
void runOn (AST::IfStmt &) override
void runOn (AST::WhileLoop &) override
void runOn (AST::BasicTypeStmt &) override
void runOn (AST::FunctionCallExpr &) override
void runOn (AST::ConstIntExpr &) override
void runOn (AST::VariableExpr &) override
Public Member Functions inherited from AST::ASTPass
ASTPass (AbstractSyntaxTree &ast)
virtual ~ASTPass ()
template<class T >
void tryRunOn (T &t)
virtual void runOn (Statement &)
virtual void runOn (TypeStmt &)
virtual void runOn (Expression &)
Protected Attributes
AST::Block * currentBlock
bool onlyInsertDeclarations
Protected Attributes inherited from AST::ASTPass
AbstractSyntaxTree & ast
Additional Inherited Members
Protected Member Functions inherited from AST::ASTPass
void handleError (ASTElement &elem, const ASTError &err)
Detailed Description
Resolve string identifiers of variables and functions.
Definition at line 17 of file IdentifierPass.hpp.
Constructor & Destructor Documentation
IdentifierPass()
IdentifierPass::IdentifierPass (AST::AbstractSyntaxTree & ast) explicit
Definition at line 22 of file IdentifierPass.cpp.
~IdentifierPass()
virtual Passes::IdentifierPass::~IdentifierPass () inline virtual
Definition at line 25 of file IdentifierPass.hpp.
References run(), and runOn().
Member Function Documentation
run()
void IdentifierPass::run () override virtual
Implements AST::ASTPass.
Definition at line 26 of file IdentifierPass.cpp.
References AST::ASTPass::ast, currentBlock, AST::AbstractSyntaxTree::getDeclarations(), AST::AbstractSyntaxTree::getStdLibFunctionDecls(), and onlyInsertDeclarations.
Referenced by ~IdentifierPass().
runOn() [1/12]
void IdentifierPass::runOn (AST::FunctionDecl & funcDecl) override virtual
Reimplemented from AST::ASTPass.
Definition at line 42 of file IdentifierPass.cpp.
References AST::ASTPass::ast, AST::ASTMap< T >::find(), AST::ASTElement::getCodeLocation(), AST::FunctionDecl::getParameters(), AST::FunctionDecl::getReturnTypeStmt(), and AST::AbstractSyntaxTree::getTypes().
Referenced by ~IdentifierPass().
runOn() [2/12]
void IdentifierPass::runOn (AST::FunctionDef & func) override virtual
Reimplemented from AST::ASTPass.
Definition at line 57 of file IdentifierPass.cpp.
References AST::ASTPass::ast, currentBlock, AST::FunctionDef::getBody(), AST::ASTElement::getCodeLocation(), AST::FunctionDef::getFunctionDecl(), AST::AbstractSyntaxTree::getFunctionDefs(), and onlyInsertDeclarations.
runOn() [3/12]
void IdentifierPass::runOn (AST::ReturnStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 69 of file IdentifierPass.cpp.
References AST::ReturnStmt::getValue().
runOn() [4/12]
void IdentifierPass::runOn (AST::VariableDefStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 73 of file IdentifierPass.cpp.
References currentBlock, AST::ASTElement::getCodeLocation(), AST::VariableDefStmt::getTypeStmt(), and AST::Block::getVariables().
runOn() [5/12]
void IdentifierPass::runOn (AST::VariableDefAssignStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 82 of file IdentifierPass.cpp.
References currentBlock, AST::ASTElement::getCodeLocation(), AST::VariableDefStmt::getTypeStmt(), AST::VariableDefAssignStmt::getValue(), and AST::Block::getVariables().
runOn() [6/12]
void IdentifierPass::runOn (AST::Block & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 88 of file IdentifierPass.cpp.
References currentBlock, AST::Block::getStatements(), and AST::Block::runPass().
runOn() [7/12]
void IdentifierPass::runOn (AST::IfStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 97 of file IdentifierPass.cpp.
References AST::IfStmt::getBody(), and AST::IfStmt::getCondition().
runOn() [8/12]
void IdentifierPass::runOn (AST::WhileLoop & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 102 of file IdentifierPass.cpp.
References AST::WhileLoop::getBody(), AST::WhileLoop::getCondition(), and AST::Block::runPass().
runOn() [9/12]
void IdentifierPass::runOn (AST::BasicTypeStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 107 of file IdentifierPass.cpp.
References AST::ASTPass::ast, AST::ASTMap< T >::find(), AST::ASTElement::getCodeLocation(), AST::BasicTypeStmt::getName(), AST::AbstractSyntaxTree::getTypes(), and AST::TypeStmt::setType().
runOn() [10/12]
void IdentifierPass::runOn (AST::FunctionCallExpr & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 115 of file IdentifierPass.cpp.
References AST::ASTPass::ast, AST::ASTMap< T >::find(), AST::FunctionCallExpr::getArgs(), AST::ASTElement::getCodeLocation(), AST::FunctionCallExpr::getName(), AST::FunctionDecl::getParameters(), AST::AbstractSyntaxTree::getTypes(), and AST::FunctionCallExpr::setFunctionDecl().
runOn() [11/12]
void IdentifierPass::runOn (AST::ConstIntExpr & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 137 of file IdentifierPass.cpp.
References AST::ConstIntExpr::getTypeStmt().
runOn() [12/12]
void IdentifierPass::runOn (AST::VariableExpr & stmt) override virtual
Todo:
Copy variables from parent blocks in runOn(Block), or search through parent blocks here
Reimplemented from AST::ASTPass.
Definition at line 141 of file IdentifierPass.cpp.
References currentBlock, AST::ASTElement::getCodeLocation(), AST::VariableExpr::getName(), AST::Block::getVariables(), and AST::VariableExpr::setVariableDefStmt().
Member Data Documentation
currentBlock
AST::Block* Passes::IdentifierPass::currentBlock protected
Definition at line 20 of file IdentifierPass.hpp.
Referenced by run(), and runOn().
onlyInsertDeclarations
bool Passes::IdentifierPass::onlyInsertDeclarations protected
Definition at line 21 of file IdentifierPass.hpp.
Referenced by run(), and runOn().
The documentation for this class was generated from the following files:
auc/Passes/IdentifierPass.hpp
auc/Passes/IdentifierPass.cpp