AUC: AST::IfStmt Class Reference
AST::IfStmt Class Reference
#include <Blocks.hpp>
Public Member Functions
IfStmt (ExpressionPtr condition, BlockPtr body, CodeLocation codeLocation)
virtual ~IfStmt ()
virtual void runPass (ASTPass &pass)
ExpressionPtr getCondition ()
BlockPtr & getBody ()
Public Member Functions inherited from AST::Statement
Statement (CodeLocation codeLocation)
virtual ~Statement ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Protected Attributes
ExpressionPtr condition
BlockPtr body
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 38 of file Blocks.hpp.
Constructor & Destructor Documentation
IfStmt()
IfStmt::IfStmt (ExpressionPtr condition, BlockPtr body, CodeLocation codeLocation)
Definition at line 35 of file Blocks.cpp.
~IfStmt()
virtual AST::IfStmt::~IfStmt () inline virtual
Definition at line 46 of file Blocks.hpp.
References AST::Block::runPass().
Member Function Documentation
getBody()
BlockPtr & IfStmt::getBody ()
Definition at line 43 of file Blocks.cpp.
References body.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
getCondition()
ExpressionPtr IfStmt::getCondition ()
Definition at line 39 of file Blocks.cpp.
References condition.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
runPass()
void IfStmt::runPass (ASTPass & pass) virtual
Implements AST::Statement.
Definition at line 47 of file Blocks.cpp.
References AST::ASTPass::tryRunOn().
Member Data Documentation
body
BlockPtr AST::IfStmt::body protected
Definition at line 42 of file Blocks.hpp.
Referenced by getBody(), and AST::WhileLoop::getBody().
condition
ExpressionPtr AST::IfStmt::condition protected
Definition at line 41 of file Blocks.hpp.
Referenced by getCondition(), and AST::WhileLoop::getCondition().
The documentation for this class was generated from the following files:
auc/AST/Blocks.hpp
auc/AST/Blocks.cpp