AUC: AST::WhileLoop Class Reference
AST::WhileLoop Class Reference
#include <Blocks.hpp>
Public Member Functions
WhileLoop (ASTPtr< Expression > condition, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)
ASTPtr< Expression > getCondition ()
Block & getBody ()
Public Member Functions inherited from AST::Statement
Statement (Block *parentBlock, CodeLocation codeLocation)
Block * getParentBlock ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
ASTPtr< Expression > condition
Block body
Protected Attributes inherited from AST::Statement
Block * parentBlock
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 54 of file Blocks.hpp.
Constructor & Destructor Documentation
AST::WhileLoop::WhileLoop (ASTPtr< Expression > condition, CodeLocation codeLocation)
Member Function Documentation
Block & WhileLoop::getBody ()
Definition at line 51 of file Blocks.cpp.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
ASTPtr< Expression > WhileLoop::getCondition ()
Definition at line 47 of file Blocks.cpp.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
void WhileLoop::runPass (ASTPass & pass) virtual
Implements AST::ASTElement.
Definition at line 55 of file Blocks.cpp.
References AST::ASTPass::runOn().
Member Data Documentation
Block AST::WhileLoop::body protected
Definition at line 58 of file Blocks.hpp.
ASTPtr<Expression> AST::WhileLoop::condition protected
Definition at line 57 of file Blocks.hpp.
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Blocks.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Blocks.cpp