AUC: AST::MethodDef Class Reference
AST::MethodDef Class Reference
#include <Declarations.hpp>
Public Member Functions
MethodDef (ASTPtr< TypeStmt > returnTypeStmt, std::string name, ASTPtr< TypeStmt > objectTypeStmt, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)
ASTPtr< TypeStmt > getObjectTypeStmt ()
Public Member Functions inherited from AST::Declaration
Declaration (ASTPtr< TypeStmt > returnTypeStmt, std::string name, CodeLocation codeLocation)
std::string getName ()
ASTPtr< TypeStmt > getReturnTypeStmt ()
VariableDefStmtList & getParameters ()
Block & getBody ()
llvm::Function * getLLVMFunction ()
void setLLVMFunction (llvm::Function *llvmFunction)
std::vector< llvm::Type * > & getParameterLLVMTypes ()
bool getExported ()
void setExported (bool exported)
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
ASTPtr< TypeStmt > objectTypeStmt
Protected Attributes inherited from AST::Declaration
std::string name
ASTPtr< TypeStmt > returnTypeStmt
ASTList< VariableDefStmt > parameters
Block body
llvm::Function * llvmFunction
std::vector< llvm::Type * > parameterLLVMTypes
bool exported
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 66 of file Declarations.hpp.
Constructor & Destructor Documentation
MethodDef::MethodDef (ASTPtr< TypeStmt > returnTypeStmt, std::string name, ASTPtr< TypeStmt > objectTypeStmt, CodeLocation codeLocation)
Definition at line 67 of file Declarations.cpp.
References AST::Declaration::body, AST::Declaration::getName(), AST::Declaration::name, AST::CodeLocation::none, and AST::Declaration::parameters.
Member Function Documentation
ASTPtr< TypeStmt > MethodDef::getObjectTypeStmt ()
Definition at line 81 of file Declarations.cpp.
References objectTypeStmt.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
void MethodDef::runPass (ASTPass & pass) virtual
Implements AST::Declaration.
Definition at line 77 of file Declarations.cpp.
References AST::ASTPass::runOn().
Member Data Documentation
ASTPtr<TypeStmt> AST::MethodDef::objectTypeStmt protected
Definition at line 69 of file Declarations.hpp.
Referenced by getObjectTypeStmt().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Declarations.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Declarations.cpp