AUC: AST::VariableDefAssignStmt Class Reference
AST::VariableDefAssignStmt Class Reference
#include <Statements.hpp>
Public Member Functions
VariableDefAssignStmt (ASTPtr< TypeStmt > type, std::string name, ASTPtr< Expression > value, Block *parentBlock, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)
ASTPtr< Expression > getValue ()
Public Member Functions inherited from AST::VariableDefStmt
VariableDefStmt (ASTPtr< TypeStmt > typeStmt, std::string name, Block *parentBlock, CodeLocation codeLocation)
std::string getName ()
ASTPtr< TypeStmt > getTypeStmt ()
llvm::AllocaInst * getAllocaInst ()
void setAllocaInst (llvm::AllocaInst *allocaInst)
Public Member Functions inherited from AST::Statement
Statement (Block *parentBlock, CodeLocation codeLocation)
Block * getParentBlock ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
ASTPtr< Expression > value
Protected Attributes inherited from AST::VariableDefStmt
ASTPtr< TypeStmt > typeStmt
std::string name
llvm::AllocaInst * allocaInst
Protected Attributes inherited from AST::Statement
Block * parentBlock
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 70 of file Statements.hpp.
Constructor & Destructor Documentation
VariableDefAssignStmt::VariableDefAssignStmt (ASTPtr< TypeStmt > type, std::string name, ASTPtr< Expression > value, Block * parentBlock, CodeLocation codeLocation)
Definition at line 62 of file Statements.cpp.
Member Function Documentation
ASTPtr< Expression > VariableDefAssignStmt::getValue ()
Definition at line 72 of file Statements.cpp.
References value.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
void VariableDefAssignStmt::runPass (ASTPass & pass) virtual
Reimplemented from AST::VariableDefStmt.
Definition at line 68 of file Statements.cpp.
References AST::ASTPass::runOn().
Member Data Documentation
ASTPtr<Expression> AST::VariableDefAssignStmt::value protected
Definition at line 73 of file Statements.hpp.
Referenced by getValue().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Statements.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Statements.cpp