AUC: AST::AbstractSyntaxTree Class Reference
AST::AbstractSyntaxTree Class Reference
#include <AbstractSyntaxTree.hpp>
Public Member Functions
AbstractSyntaxTree ()
DeclarationList & getDeclarations ()
ASTMap< FunctionDef * > & getFunctionDefs ()
ASTMap< ASTPtr< Type > > & getTypes ()
ASTMap< ASTPtr< MethodDef > > & getStdLibMethodDefs ()
llvm::LLVMContext & getLLVMContext ()
llvm::IRBuilder & getIRBuilder ()
llvm::Module & getLLVMModule ()
Protected Attributes
DeclarationList declarations
ASTMap< FunctionDef * > functionDefs
ASTMap< ASTPtr< Type > > types
ASTMap< ASTPtr< MethodDef > > stdLibMethodDefs
llvm::LLVMContext llvmContext
llvm::IRBuilder irBuilder
std::unique_ptr< llvm::Module > llvmModule
Detailed Description
Definition at line 20 of file AbstractSyntaxTree.hpp.
Constructor & Destructor Documentation
AbstractSyntaxTree::AbstractSyntaxTree ()
Definition at line 11 of file AbstractSyntaxTree.cpp.
References llvmContext, and llvmModule.
Member Function Documentation
DeclarationList & AbstractSyntaxTree::getDeclarations ()
Definition at line 15 of file AbstractSyntaxTree.cpp.
References declarations.
Referenced by Passes::TypePass::run(), Passes::IdentifierPass::run(), Passes::VerifyOptimizePass::run(), Passes::PrintPass::run(), and Passes::LLVMPass::run().
ASTMap< FunctionDef * > & AbstractSyntaxTree::getFunctionDefs ()
Definition at line 19 of file AbstractSyntaxTree.cpp.
References functionDefs.
Referenced by Passes::IdentifierPass::run(), and Passes::IdentifierPass::runOn().
llvm::IRBuilder & AbstractSyntaxTree::getIRBuilder ()
Definition at line 31 of file AbstractSyntaxTree.cpp.
References irBuilder.
llvm::LLVMContext & AbstractSyntaxTree::getLLVMContext ()
Definition at line 35 of file AbstractSyntaxTree.cpp.
References llvmContext.
llvm::Module & AbstractSyntaxTree::getLLVMModule ()
Definition at line 39 of file AbstractSyntaxTree.cpp.
References llvmModule.
Referenced by Passes::IRExportPass::run(), Passes::VerifyOptimizePass::run(), Passes::LLVMPass::runOn(), and Passes::VerifyOptimizePass::VerifyOptimizePass().
ASTMap< ASTPtr< MethodDef > > & AbstractSyntaxTree::getStdLibMethodDefs ()
Definition at line 27 of file AbstractSyntaxTree.cpp.
References stdLibMethodDefs.
Referenced by Passes::LLVMPass::addScalarMethods(), and Passes::StdLibPass::addScalarTypes().
ASTMap< ASTPtr< Type > > & AbstractSyntaxTree::getTypes ()
Definition at line 23 of file AbstractSyntaxTree.cpp.
References types.
Referenced by Passes::LLVMPass::createLLVMTypes(), and Passes::IdentifierPass::runOn().
Member Data Documentation
DeclarationList AST::AbstractSyntaxTree::declarations protected
Definition at line 23 of file AbstractSyntaxTree.hpp.
Referenced by getDeclarations().
ASTMap<FunctionDef*> AST::AbstractSyntaxTree::functionDefs protected
Definition at line 24 of file AbstractSyntaxTree.hpp.
Referenced by getFunctionDefs().
llvm::IRBuilder AST::AbstractSyntaxTree::irBuilder protected
Definition at line 29 of file AbstractSyntaxTree.hpp.
Referenced by getIRBuilder().
llvm::LLVMContext AST::AbstractSyntaxTree::llvmContext protected
Definition at line 28 of file AbstractSyntaxTree.hpp.
Referenced by AbstractSyntaxTree(), and getLLVMContext().
std::unique_ptr<llvm::Module> AST::AbstractSyntaxTree::llvmModule protected
Definition at line 30 of file AbstractSyntaxTree.hpp.
Referenced by AbstractSyntaxTree(), and getLLVMModule().
ASTMap<ASTPtr<MethodDef> > AST::AbstractSyntaxTree::stdLibMethodDefs protected
Definition at line 26 of file AbstractSyntaxTree.hpp.
Referenced by getStdLibMethodDefs().
ASTMap<ASTPtr<Type> > AST::AbstractSyntaxTree::types protected
Definition at line 25 of file AbstractSyntaxTree.hpp.
Referenced by getTypes().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/AbstractSyntaxTree.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/AbstractSyntaxTree.cpp