AUC: type::Type Class Reference
type::Type Class Reference abstract
#include <Type.hpp>
Public Member Functions
virtual ~Type ()
virtual std::string getName ()=0
virtual size_t getSize ()=0
AST::ASTMap< AST::FunctionDecl * > & getFunctionDecls ()
Protected Attributes
AST::ASTMap< AST::FunctionDecl * > functionDecls
Detailed Description
Definition at line 17 of file Type.hpp.
Constructor & Destructor Documentation
~Type()
virtual type::Type::~Type () inline virtual
Definition at line 23 of file Type.hpp.
References getFunctionDecls(), getName(), and getSize().
Member Function Documentation
getFunctionDecls()
AST::ASTMap< AST::FunctionDecl * > & Type::getFunctionDecls ()
Definition at line 11 of file Type.cpp.
References functionDecls.
Referenced by ~Type().
getName()
virtual std::string type::Type::getName () pure virtual
Implemented in type::ScalarType.
Referenced by ~Type().
getSize()
virtual size_t type::Type::getSize () pure virtual
Implemented in type::ScalarType.
Referenced by ~Type().
Member Data Documentation
functionDecls
AST::ASTMap<AST::FunctionDecl*> type::Type::functionDecls protected
Definition at line 20 of file Type.hpp.
Referenced by getFunctionDecls().
The documentation for this class was generated from the following files:
auc/Types/Type.hpp
auc/Types/Type.cpp