AUC: AST::TypeStmt Class Reference
AST::TypeStmt Class Reference
#include <TypeStmt.hpp>
Public Member Functions
virtual ~TypeStmt ()
type::TypePtr getType ()
void setType (type::TypePtr type)
bool getIsReference ()
void setIsReference (bool isReference)
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
virtual void runPass (ASTPass &pass)=0
CodeLocation getCodeLocation ()
Protected Member Functions
TypeStmt (CodeLocation codeLocation)
Protected Attributes
type::TypePtr type
bool isReference
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 18 of file TypeStmt.hpp.
Constructor & Destructor Documentation
TypeStmt()
TypeStmt::TypeStmt (CodeLocation codeLocation) protected
Definition at line 13 of file TypeStmt.cpp.
~TypeStmt()
virtual AST::TypeStmt::~TypeStmt () inline virtual
Definition at line 27 of file TypeStmt.hpp.
References getIsReference(), getType(), setIsReference(), and setType().
Member Function Documentation
getIsReference()
bool TypeStmt::getIsReference ()
Definition at line 25 of file TypeStmt.cpp.
References isReference.
Referenced by Passes::OutputPass::runOn(), and ~TypeStmt().
getType()
TypePtr TypeStmt::getType ()
Definition at line 17 of file TypeStmt.cpp.
References type.
Referenced by ~TypeStmt().
setIsReference()
void TypeStmt::setIsReference (bool isReference)
Definition at line 29 of file TypeStmt.cpp.
References isReference.
Referenced by ~TypeStmt().
setType()
void TypeStmt::setType (type::TypePtr type)
Definition at line 21 of file TypeStmt.cpp.
References type.
Referenced by Passes::IdentifierPass::runOn(), and ~TypeStmt().
Member Data Documentation
isReference
bool AST::TypeStmt::isReference protected
Definition at line 22 of file TypeStmt.hpp.
Referenced by getIsReference(), and setIsReference().
type
type::TypePtr AST::TypeStmt::type protected
Definition at line 21 of file TypeStmt.hpp.
Referenced by getType(), and setType().
The documentation for this class was generated from the following files:
auc/AST/TypeStmt.hpp
auc/AST/TypeStmt.cpp