AUC: AST::FunctionCallExpr Class Reference
AST::FunctionCallExpr Class Reference
#include <Expressions.hpp>
Public Member Functions
FunctionCallExpr (std::string name, CodeLocation codeLocation)
virtual ~FunctionCallExpr ()
void runPass (ASTPass &pass) override
type::TypePtr getType () override
bool getIsReference () override
bool getIsReferenceable () override
std::string getName ()
ASTList< Expression > & getArgs ()
FunctionDecl * getFunctionDecl ()
void setFunctionDecl (FunctionDecl *functionDecl)
Public Member Functions inherited from AST::Expression
Expression (CodeLocation codeLocation)
virtual ~Expression ()
Public Member Functions inherited from AST::Statement
Statement (CodeLocation codeLocation)
virtual ~Statement ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Protected Attributes
std::string name
ASTList< Expression > args
FunctionDecl * functionDecl
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 33 of file Expressions.hpp.
Constructor & Destructor Documentation
FunctionCallExpr()
FunctionCallExpr::FunctionCallExpr (std::string name, CodeLocation codeLocation)
Definition at line 18 of file Expressions.cpp.
~FunctionCallExpr()
virtual AST::FunctionCallExpr::~FunctionCallExpr () inline virtual
Definition at line 43 of file Expressions.hpp.
References AST::Expression::getIsReference(), AST::Expression::getIsReferenceable(), AST::Expression::getType(), and AST::Expression::runPass().
Member Function Documentation
getArgs()
ASTList< Expression > & FunctionCallExpr::getArgs ()
Definition at line 43 of file Expressions.cpp.
References args.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
getFunctionDecl()
FunctionDecl * FunctionCallExpr::getFunctionDecl ()
Definition at line 47 of file Expressions.cpp.
References functionDecl.
Referenced by Passes::TypePass::runOn(), and Passes::OutputPass::runOn().
getIsReference()
bool FunctionCallExpr::getIsReference () override virtual
Implements AST::Expression.
Definition at line 30 of file Expressions.cpp.
References functionDecl, and AST::FunctionDecl::getReturnTypeStmt().
getIsReferenceable()
bool FunctionCallExpr::getIsReferenceable () override virtual
Implements AST::Expression.
Definition at line 34 of file Expressions.cpp.
getName()
std::string FunctionCallExpr::getName ()
Definition at line 39 of file Expressions.cpp.
References name.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
getType()
TypePtr FunctionCallExpr::getType () override virtual
Implements AST::Expression.
Definition at line 26 of file Expressions.cpp.
References functionDecl, and AST::FunctionDecl::getReturnTypeStmt().
runPass()
void FunctionCallExpr::runPass (ASTPass & pass) override virtual
Implements AST::Expression.
Definition at line 22 of file Expressions.cpp.
References AST::ASTPass::tryRunOn().
setFunctionDecl()
void FunctionCallExpr::setFunctionDecl (FunctionDecl * functionDecl)
Definition at line 51 of file Expressions.cpp.
References functionDecl.
Referenced by Passes::IdentifierPass::runOn().
Member Data Documentation
args
ASTList<Expression> AST::FunctionCallExpr::args protected
Definition at line 37 of file Expressions.hpp.
Referenced by getArgs().
functionDecl
FunctionDecl* AST::FunctionCallExpr::functionDecl protected
Definition at line 38 of file Expressions.hpp.
Referenced by getFunctionDecl(), getIsReference(), getType(), and setFunctionDecl().
name
std::string AST::FunctionCallExpr::name protected
Definition at line 36 of file Expressions.hpp.
Referenced by getName().
The documentation for this class was generated from the following files:
auc/AST/Expressions.hpp
auc/AST/Expressions.cpp