AUC: AST::ConstIntExpr Class Reference
AST::ConstIntExpr Class Reference
#include <Expressions.hpp>
Public Member Functions
ConstIntExpr (std::string valueStr, uint8_t numValue, CodeLocation codeLocation)
ConstIntExpr (std::string valueStr, int8_t numValue, CodeLocation codeLocation)
ConstIntExpr (std::string valueStr, uint16_t numValue, CodeLocation codeLocation)
ConstIntExpr (std::string valueStr, int16_t numValue, CodeLocation codeLocation)
ConstIntExpr (std::string valueStr, uint32_t numValue, CodeLocation codeLocation)
ConstIntExpr (std::string valueStr, int32_t numValue, CodeLocation codeLocation)
ConstIntExpr (std::string valueStr, uint64_t numValue, CodeLocation codeLocation)
ConstIntExpr (std::string valueStr, int64_t numValue, CodeLocation codeLocation)
virtual ~ConstIntExpr ()
void runPass (ASTPass &pass) override
type::TypePtr getType () override
bool getIsReference () override
bool getIsReferenceable () override
std::string getValueStr ()
uint64_t getNumValue ()
TypeStmtPtr getTypeStmt ()
Public Member Functions inherited from AST::Expression
Expression (CodeLocation codeLocation)
virtual ~Expression ()
Public Member Functions inherited from AST::Statement
Statement (CodeLocation codeLocation)
virtual ~Statement ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Protected Attributes
std::string valueStr
uint64_t numValue
TypeStmtPtr typeStmt
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 58 of file Expressions.hpp.
Constructor & Destructor Documentation
ConstIntExpr() [1/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, uint8_t numValue, CodeLocation codeLocation)
Definition at line 56 of file Expressions.cpp.
ConstIntExpr() [2/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, int8_t numValue, CodeLocation codeLocation)
Definition at line 61 of file Expressions.cpp.
ConstIntExpr() [3/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, uint16_t numValue, CodeLocation codeLocation)
Definition at line 66 of file Expressions.cpp.
ConstIntExpr() [4/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, int16_t numValue, CodeLocation codeLocation)
Definition at line 71 of file Expressions.cpp.
ConstIntExpr() [5/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, uint32_t numValue, CodeLocation codeLocation)
Definition at line 76 of file Expressions.cpp.
ConstIntExpr() [6/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, int32_t numValue, CodeLocation codeLocation)
Definition at line 81 of file Expressions.cpp.
ConstIntExpr() [7/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, uint64_t numValue, CodeLocation codeLocation)
Definition at line 86 of file Expressions.cpp.
ConstIntExpr() [8/8]
ConstIntExpr::ConstIntExpr (std::string valueStr, int64_t numValue, CodeLocation codeLocation)
Definition at line 91 of file Expressions.cpp.
~ConstIntExpr()
virtual AST::ConstIntExpr::~ConstIntExpr () inline virtual
Definition at line 82 of file Expressions.hpp.
References AST::Expression::getIsReference(), AST::Expression::getIsReferenceable(), AST::Expression::getType(), and AST::Expression::runPass().
Member Function Documentation
getIsReference()
bool ConstIntExpr::getIsReference () override virtual
Implements AST::Expression.
Definition at line 104 of file Expressions.cpp.
getIsReferenceable()
bool ConstIntExpr::getIsReferenceable () override virtual
Implements AST::Expression.
Definition at line 108 of file Expressions.cpp.
getNumValue()
uint64_t ConstIntExpr::getNumValue ()
Definition at line 116 of file Expressions.cpp.
References numValue.
getType()
TypePtr ConstIntExpr::getType () override virtual
Implements AST::Expression.
Definition at line 100 of file Expressions.cpp.
References typeStmt.
getTypeStmt()
TypeStmtPtr ConstIntExpr::getTypeStmt ()
Definition at line 120 of file Expressions.cpp.
References typeStmt.
Referenced by Passes::TypePass::runOn(), and Passes::IdentifierPass::runOn().
getValueStr()
std::string ConstIntExpr::getValueStr ()
Definition at line 112 of file Expressions.cpp.
References valueStr.
Referenced by Passes::OutputPass::runOn().
runPass()
void ConstIntExpr::runPass (ASTPass & pass) override virtual
Implements AST::Expression.
Definition at line 96 of file Expressions.cpp.
References AST::ASTPass::tryRunOn().
Member Data Documentation
numValue
uint64_t AST::ConstIntExpr::numValue protected
Definition at line 62 of file Expressions.hpp.
Referenced by getNumValue().
typeStmt
TypeStmtPtr AST::ConstIntExpr::typeStmt protected
Definition at line 63 of file Expressions.hpp.
Referenced by getType(), and getTypeStmt().
valueStr
std::string AST::ConstIntExpr::valueStr protected
Definition at line 61 of file Expressions.hpp.
Referenced by getValueStr().
The documentation for this class was generated from the following files:
auc/AST/Expressions.hpp
auc/AST/Expressions.cpp