AUC: Passes::PrintPass Class Reference
Passes::PrintPass Class Reference
Print an AST with type information and indentation to an output stream.
#include <PrintPass.hpp>
Public Member Functions
PrintPass (AST::AbstractSyntaxTree &ast, std::ostream &stream)
virtual void run ()
virtual void runOn (AST::FunctionDef &)
virtual void runOn (AST::MethodDef &)
virtual void runOn (AST::ReturnStmt &)
virtual void runOn (AST::VariableDefStmt &)
virtual void runOn (AST::VariableDefAssignStmt &)
virtual void runOn (AST::Block &)
virtual void runOn (AST::IfStmt &)
virtual void runOn (AST::WhileLoop &)
virtual void runOn (AST::TypeStmt &)
virtual void runOn (AST::FunctionCallExpr &)
virtual void runOn (AST::MethodCallExpr &)
virtual void runOn (AST::ConstIntExpr &)
virtual void runOn (AST::VariableExpr &)
Public Member Functions inherited from AST::ASTPass
ASTPass (AbstractSyntaxTree &ast)
virtual void runOn (Declaration &)
virtual void runOn (Statement &)
virtual void runOn (Expression &)
Additional Inherited Members
Protected Attributes inherited from AST::ASTPass
AbstractSyntaxTree & ast
Detailed Description
Print an AST with type information and indentation to an output stream.
Definition at line 18 of file PrintPass.hpp.
Constructor & Destructor Documentation
PrintPass::PrintPass (AST::AbstractSyntaxTree & ast, std::ostream & stream)
Definition at line 18 of file PrintPass.cpp.
Member Function Documentation
void PrintPass::run () virtual
Implements AST::ASTPass.
Definition at line 30 of file PrintPass.cpp.
References AST::ASTPass::ast, and AST::AbstractSyntaxTree::getDeclarations().
void PrintPass::runOn (AST::FunctionDef & func) virtual
Reimplemented from AST::ASTPass.
Definition at line 43 of file PrintPass.cpp.
References AST::Declaration::getBody(), AST::Declaration::getName(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), and AST::Block::runPass().
void PrintPass::runOn (AST::MethodDef & func) virtual
Reimplemented from AST::ASTPass.
Definition at line 59 of file PrintPass.cpp.
References AST::Declaration::getBody(), AST::Declaration::getName(), AST::MethodDef::getObjectTypeStmt(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), and AST::Block::runPass().
void PrintPass::runOn (AST::ReturnStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 77 of file PrintPass.cpp.
References AST::ReturnStmt::getValue().
void PrintPass::runOn (AST::VariableDefStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 83 of file PrintPass.cpp.
References AST::VariableDefStmt::getName(), and AST::VariableDefStmt::getTypeStmt().
void PrintPass::runOn (AST::VariableDefAssignStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 89 of file PrintPass.cpp.
References AST::VariableDefStmt::getName(), AST::VariableDefStmt::getTypeStmt(), and AST::VariableDefAssignStmt::getValue().
void PrintPass::runOn (AST::Block & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 97 of file PrintPass.cpp.
References AST::Block::getStatements().
void PrintPass::runOn (AST::IfStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 109 of file PrintPass.cpp.
References AST::IfStmt::getBody(), AST::IfStmt::getCondition(), and AST::Block::runPass().
void PrintPass::runOn (AST::WhileLoop & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 116 of file PrintPass.cpp.
References AST::WhileLoop::getBody(), AST::WhileLoop::getCondition(), and AST::Block::runPass().
void PrintPass::runOn (AST::TypeStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 123 of file PrintPass.cpp.
References AST::TypeStmt::getName().
void PrintPass::runOn (AST::FunctionCallExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 127 of file PrintPass.cpp.
References AST::FunctionCallExpr::getArgs(), and AST::FunctionCallExpr::getName().
void PrintPass::runOn (AST::MethodCallExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 140 of file PrintPass.cpp.
References AST::MethodCallExpr::getArgs(), AST::MethodCallExpr::getName(), and AST::MethodCallExpr::getObjectExpr().
void PrintPass::runOn (AST::ConstIntExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 155 of file PrintPass.cpp.
References AST::ConstIntExpr::getValueStr().
void PrintPass::runOn (AST::VariableExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 159 of file PrintPass.cpp.
References AST::VariableExpr::getName().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/PrintPass.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/PrintPass.cpp