AUC: AST::VariableExpr Class Reference
AST::VariableExpr Class Reference
#include <Expressions.hpp>
Public Member Functions
VariableExpr (std::string name, CodeLocation codeLocation)
virtual ~VariableExpr ()
void runPass (ASTPass &pass) override
type::TypePtr getType () override
bool getIsReference () override
bool getIsReferenceable () override
std::string getName ()
VariableDefStmt * getVariableDefStmt ()
void setVariableDefStmt (VariableDefStmt *variableDefStmt)
Public Member Functions inherited from AST::Expression
Expression (CodeLocation codeLocation)
virtual ~Expression ()
Public Member Functions inherited from AST::Statement
Statement (CodeLocation codeLocation)
virtual ~Statement ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Protected Attributes
std::string name
VariableDefStmt * variableDefStmt
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 97 of file Expressions.hpp.
Constructor & Destructor Documentation
VariableExpr()
VariableExpr::VariableExpr (std::string name, CodeLocation codeLocation)
Definition at line 125 of file Expressions.cpp.
~VariableExpr()
virtual AST::VariableExpr::~VariableExpr () inline virtual
Definition at line 106 of file Expressions.hpp.
References AST::Expression::getIsReference(), AST::Expression::getIsReferenceable(), AST::Expression::getType(), and AST::Expression::runPass().
Member Function Documentation
getIsReference()
bool VariableExpr::getIsReference () override virtual
Implements AST::Expression.
Definition at line 138 of file Expressions.cpp.
References AST::VariableDefStmt::getTypeStmt(), and variableDefStmt.
getIsReferenceable()
bool VariableExpr::getIsReferenceable () override virtual
Implements AST::Expression.
Definition at line 142 of file Expressions.cpp.
References AST::VariableDefStmt::getTypeStmt(), and variableDefStmt.
getName()
std::string VariableExpr::getName ()
Definition at line 147 of file Expressions.cpp.
References name.
Referenced by Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
getType()
TypePtr VariableExpr::getType () override virtual
Implements AST::Expression.
Definition at line 134 of file Expressions.cpp.
References AST::VariableDefStmt::getTypeStmt(), and variableDefStmt.
getVariableDefStmt()
VariableDefStmt * VariableExpr::getVariableDefStmt ()
Definition at line 151 of file Expressions.cpp.
References variableDefStmt.
runPass()
void VariableExpr::runPass (ASTPass & pass) override virtual
Implements AST::Expression.
Definition at line 130 of file Expressions.cpp.
References AST::ASTPass::tryRunOn().
setVariableDefStmt()
void VariableExpr::setVariableDefStmt (VariableDefStmt * variableDefStmt)
Definition at line 155 of file Expressions.cpp.
References variableDefStmt.
Referenced by Passes::IdentifierPass::runOn().
Member Data Documentation
name
std::string AST::VariableExpr::name protected
Definition at line 100 of file Expressions.hpp.
Referenced by getName().
variableDefStmt
VariableDefStmt* AST::VariableExpr::variableDefStmt protected
Definition at line 101 of file Expressions.hpp.
Referenced by getIsReference(), getIsReferenceable(), getType(), getVariableDefStmt(), and setVariableDefStmt().
The documentation for this class was generated from the following files:
auc/AST/Expressions.hpp
auc/AST/Expressions.cpp