AUC: Passes::LLVMPass Class Reference
Passes::LLVMPass Class Reference
Generate LLVM Intermediate Representation.
#include <LLVMPass.hpp>
Public Member Functions
LLVMPass (AST::AbstractSyntaxTree &ast)
virtual void run ()
virtual void runOn (AST::FunctionDef &)
virtual void runOn (AST::MethodDef &)
virtual void runOn (AST::ReturnStmt &)
virtual void runOn (AST::VariableDefStmt &)
virtual void runOn (AST::VariableDefAssignStmt &)
virtual void runOn (AST::Block &)
virtual void runOn (AST::IfStmt &)
virtual void runOn (AST::WhileLoop &)
virtual void runOn (AST::TypeStmt &)
virtual void runOn (AST::FunctionCallExpr &)
virtual void runOn (AST::MethodCallExpr &)
virtual void runOn (AST::ConstIntExpr &)
virtual void runOn (AST::VariableExpr &)
Public Member Functions inherited from AST::ASTPass
ASTPass (AbstractSyntaxTree &ast)
virtual void runOn (Declaration &)
virtual void runOn (Statement &)
virtual void runOn (Expression &)
Protected Member Functions
void createLLVMTypes ()
void addScalarMethods ()
Protected Attributes
llvm::LLVMContext & llvmContext
llvm::IRBuilder & irBuilder
bool onlyInsertDeclarations
Protected Attributes inherited from AST::ASTPass
AbstractSyntaxTree & ast
Detailed Description
Generate LLVM Intermediate Representation.
Definition at line 19 of file LLVMPass.hpp.
Constructor & Destructor Documentation
LLVMPass::LLVMPass (AST::AbstractSyntaxTree & ast)
Definition at line 24 of file LLVMPass.cpp.
Member Function Documentation
void LLVMPass::addScalarMethods () protected
Definition at line 35 of file LLVMPass.cpp.
References AST::ASTPass::ast, AST::AbstractSyntaxTree::getStdLibMethodDefs(), irBuilder, llvmContext, and onlyInsertDeclarations.
Referenced by run().
void LLVMPass::createLLVMTypes () protected
Definition at line 29 of file LLVMPass.cpp.
References AST::ASTPass::ast, AST::AbstractSyntaxTree::getTypes(), and llvmContext.
Referenced by run().
void LLVMPass::run () virtual
Implements AST::ASTPass.
Definition at line 115 of file LLVMPass.cpp.
References addScalarMethods(), AST::ASTPass::ast, createLLVMTypes(), AST::AbstractSyntaxTree::getDeclarations(), and onlyInsertDeclarations.
void LLVMPass::runOn (AST::FunctionDef & func) virtual
Create function type and function
Add alloca for each parameter
Store the initial value into the alloca
Reimplemented from AST::ASTPass.
Definition at line 128 of file LLVMPass.cpp.
References AST::ASTPass::ast, AST::Declaration::getBody(), AST::Declaration::getExported(), AST::Declaration::getLLVMFunction(), AST::AbstractSyntaxTree::getLLVMModule(), AST::Declaration::getName(), AST::Declaration::getParameterLLVMTypes(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), irBuilder, llvmContext, onlyInsertDeclarations, AST::Block::runPass(), and AST::Declaration::setLLVMFunction().
void LLVMPass::runOn (AST::MethodDef & func) virtual
Create function type and function
Add alloca for each parameter
Todo:
Set pointer of first parameter 'this'
Create no alloca for "this" pointer
Store the initial value into the alloca
Reimplemented from AST::ASTPass.
Definition at line 168 of file LLVMPass.cpp.
References AST::ASTPass::ast, AST::Declaration::getBody(), AST::Declaration::getExported(), AST::Declaration::getLLVMFunction(), AST::AbstractSyntaxTree::getLLVMModule(), AST::Declaration::getName(), AST::MethodDef::getObjectTypeStmt(), AST::Declaration::getParameterLLVMTypes(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), irBuilder, llvmContext, onlyInsertDeclarations, AST::Block::runPass(), and AST::Declaration::setLLVMFunction().
void LLVMPass::runOn (AST::ReturnStmt & stmt) virtual
Return by-value
Reimplemented from AST::ASTPass.
Definition at line 220 of file LLVMPass.cpp.
References AST::ReturnStmt::getValue(), and irBuilder.
void LLVMPass::runOn (AST::VariableDefStmt & stmt) virtual
Create an alloca for this variable
Reimplemented from AST::ASTPass.
Definition at line 232 of file LLVMPass.cpp.
References AST::VariableDefStmt::getName(), AST::VariableDefStmt::getTypeStmt(), irBuilder, and AST::VariableDefStmt::setAllocaInst().
void LLVMPass::runOn (AST::VariableDefAssignStmt & stmt) virtual
Todo:
Merge getLLVMValue and getAllocaInst in Expression subclasses?
Reimplemented from AST::ASTPass.
Definition at line 240 of file LLVMPass.cpp.
References AST::VariableDefStmt::getName(), AST::VariableDefStmt::getTypeStmt(), AST::VariableDefAssignStmt::getValue(), irBuilder, and AST::VariableDefStmt::setAllocaInst().
void LLVMPass::runOn (AST::Block & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 251 of file LLVMPass.cpp.
References AST::Block::getStatements().
void LLVMPass::runOn (AST::IfStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 257 of file LLVMPass.cpp.
References AST::IfStmt::getBody(), AST::IfStmt::getCondition(), and AST::Block::runPass().
void LLVMPass::runOn (AST::WhileLoop & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 262 of file LLVMPass.cpp.
References AST::WhileLoop::getBody(), AST::WhileLoop::getCondition(), and AST::Block::runPass().
void LLVMPass::runOn (AST::TypeStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 267 of file LLVMPass.cpp.
void LLVMPass::runOn (AST::FunctionCallExpr & stmt) virtual
Parameters are call-by-value
Reimplemented from AST::ASTPass.
Definition at line 270 of file LLVMPass.cpp.
References AST::FunctionCallExpr::getArgs(), AST::FunctionCallExpr::getFunctionDef(), AST::Declaration::getLLVMFunction(), irBuilder, and AST::Expression::setLLVMValue().
void LLVMPass::runOn (AST::MethodCallExpr & stmt) virtual
First parameter is call-by-reference
Other parameters are call-by-value
Reimplemented from AST::ASTPass.
Definition at line 286 of file LLVMPass.cpp.
References AST::MethodCallExpr::getArgs(), AST::Declaration::getLLVMFunction(), AST::MethodCallExpr::getMethodDef(), AST::MethodCallExpr::getObjectExpr(), irBuilder, and AST::Expression::setLLVMValue().
void LLVMPass::runOn (AST::ConstIntExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 315 of file LLVMPass.cpp.
References AST::ConstIntExpr::getNumValue(), AST::ConstIntExpr::getTypeStmt(), and AST::Expression::setLLVMValue().
void LLVMPass::runOn (AST::VariableExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 323 of file LLVMPass.cpp.
References AST::VariableDefStmt::getAllocaInst(), AST::VariableExpr::getVariableDefStmt(), and AST::Expression::setLLVMValue().
Member Data Documentation
llvm::IRBuilder& Passes::LLVMPass::irBuilder protected
Definition at line 23 of file LLVMPass.hpp.
Referenced by addScalarMethods(), and runOn().
llvm::LLVMContext& Passes::LLVMPass::llvmContext protected
Definition at line 22 of file LLVMPass.hpp.
Referenced by addScalarMethods(), createLLVMTypes(), and runOn().
bool Passes::LLVMPass::onlyInsertDeclarations protected
Definition at line 24 of file LLVMPass.hpp.
Referenced by addScalarMethods(), run(), and runOn().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/LLVMPass.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/LLVMPass.cpp