AUC: AST::FunctionDecl Class Reference
AST::FunctionDecl Class Reference
#include <Declarations.hpp>
Public Member Functions
FunctionDecl (TypeStmtPtr returnTypeStmt, std::string name, bool exported, CodeLocation codeLocation)
virtual ~FunctionDecl ()
virtual void runPass (ASTPass &pass)
std::string getName ()
TypeStmtPtr getReturnTypeStmt ()
VariableDefStmtList & getParameters ()
Public Member Functions inherited from AST::Declaration
Declaration (bool exported, CodeLocation codeLocation)
virtual ~Declaration ()
bool getExported ()
void setExported (bool exported)
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Protected Attributes
std::string name
TypeStmtPtr returnTypeStmt
ASTList< VariableDefStmt > parameters
Protected Attributes inherited from AST::Declaration
bool exported
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 31 of file Declarations.hpp.
Constructor & Destructor Documentation
FunctionDecl()
FunctionDecl::FunctionDecl (TypeStmtPtr returnTypeStmt, std::string name, bool exported, CodeLocation codeLocation)
Definition at line 28 of file Declarations.cpp.
~FunctionDecl()
virtual AST::FunctionDecl::~FunctionDecl () inline virtual
Definition at line 40 of file Declarations.hpp.
References AST::ASTElement::runPass().
Member Function Documentation
getName()
std::string FunctionDecl::getName ()
Definition at line 36 of file Declarations.cpp.
References name.
getParameters()
VariableDefStmtList & FunctionDecl::getParameters ()
Definition at line 44 of file Declarations.cpp.
References parameters.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
getReturnTypeStmt()
TypeStmtPtr FunctionDecl::getReturnTypeStmt ()
Definition at line 40 of file Declarations.cpp.
References returnTypeStmt.
Referenced by AST::FunctionCallExpr::getIsReference(), AST::FunctionCallExpr::getType(), Passes::TypePass::runOn(), and Passes::IdentifierPass::runOn().
runPass()
void FunctionDecl::runPass (ASTPass & pass) virtual
Implements AST::ASTElement.
Definition at line 32 of file Declarations.cpp.
References AST::ASTPass::tryRunOn().
Member Data Documentation
name
std::string AST::FunctionDecl::name protected
Definition at line 34 of file Declarations.hpp.
Referenced by getName().
parameters
ASTList<VariableDefStmt> AST::FunctionDecl::parameters protected
Definition at line 36 of file Declarations.hpp.
Referenced by getParameters().
returnTypeStmt
TypeStmtPtr AST::FunctionDecl::returnTypeStmt protected
Definition at line 35 of file Declarations.hpp.
Referenced by getReturnTypeStmt().
The documentation for this class was generated from the following files:
auc/AST/Declarations.hpp
auc/AST/Declarations.cpp