AUC: AST::Expression Class Reference
AST::Expression Class Reference abstract
#include <Expressions.hpp>
Public Member Functions
Expression (CodeLocation codeLocation)
virtual ~Expression ()
virtual void runPass (ASTPass &pass)=0
virtual type::TypePtr getType ()=0
virtual bool getIsReference ()=0
virtual bool getIsReferenceable ()=0
Public Member Functions inherited from AST::Statement
Statement (CodeLocation codeLocation)
virtual ~Statement ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Additional Inherited Members
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 18 of file Expressions.hpp.
Constructor & Destructor Documentation
Expression()
Expression::Expression (CodeLocation codeLocation)
Definition at line 14 of file Expressions.cpp.
~Expression()
virtual AST::Expression::~Expression () inline virtual
Definition at line 22 of file Expressions.hpp.
References getIsReference(), getIsReferenceable(), getType(), and runPass().
Member Function Documentation
getIsReference()
virtual bool AST::Expression::getIsReference () pure virtual
Implemented in AST::VariableExpr, AST::ConstIntExpr, and AST::FunctionCallExpr.
Referenced by AST::ConstIntExpr::~ConstIntExpr(), ~Expression(), AST::FunctionCallExpr::~FunctionCallExpr(), and AST::VariableExpr::~VariableExpr().
getIsReferenceable()
virtual bool AST::Expression::getIsReferenceable () pure virtual
Implemented in AST::VariableExpr, AST::ConstIntExpr, and AST::FunctionCallExpr.
Referenced by AST::ConstIntExpr::~ConstIntExpr(), ~Expression(), AST::FunctionCallExpr::~FunctionCallExpr(), and AST::VariableExpr::~VariableExpr().
getType()
virtual type::TypePtr AST::Expression::getType () pure virtual
Implemented in AST::VariableExpr, AST::ConstIntExpr, and AST::FunctionCallExpr.
Referenced by AST::ConstIntExpr::~ConstIntExpr(), ~Expression(), AST::FunctionCallExpr::~FunctionCallExpr(), and AST::VariableExpr::~VariableExpr().
runPass()
virtual void AST::Expression::runPass (ASTPass & pass) pure virtual
Implements AST::Statement.
Implemented in AST::VariableExpr, AST::ConstIntExpr, and AST::FunctionCallExpr.
Referenced by AST::ConstIntExpr::~ConstIntExpr(), ~Expression(), AST::FunctionCallExpr::~FunctionCallExpr(), and AST::VariableExpr::~VariableExpr().
The documentation for this class was generated from the following files:
auc/AST/Expressions.hpp
auc/AST/Expressions.cpp