AUC: AST::ASTPass Class Reference
AST::ASTPass Class Reference abstract
#include <ASTPass.hpp>
Public Member Functions
ASTPass (AbstractSyntaxTree &ast)
virtual void run ()=0
virtual void runOn (Declaration &)
virtual void runOn (FunctionDef &)
virtual void runOn (MethodDef &)
virtual void runOn (Statement &)
virtual void runOn (ReturnStmt &)
virtual void runOn (VariableDefStmt &)
virtual void runOn (VariableDefAssignStmt &)
virtual void runOn (Block &)
virtual void runOn (IfStmt &)
virtual void runOn (WhileLoop &)
virtual void runOn (TypeStmt &)
virtual void runOn (Expression &)
virtual void runOn (FunctionCallExpr &)
virtual void runOn (MethodCallExpr &)
virtual void runOn (ConstIntExpr &)
virtual void runOn (VariableExpr &)
Protected Attributes
AbstractSyntaxTree & ast
Detailed Description
Definition at line 14 of file ASTPass.hpp.
Constructor & Destructor Documentation
ASTPass::ASTPass (AbstractSyntaxTree & ast)
Definition at line 13 of file ASTPass.cpp.
Member Function Documentation
virtual void AST::ASTPass::run () pure virtual
Implemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
void ASTPass::runOn (Declaration & expr) virtual
Todo:
Reorganize; multiple dispatch only for virtual base classes
Definition at line 16 of file ASTPass.cpp.
Referenced by AST::TypeStmt::runPass(), AST::Block::runPass(), AST::ReturnStmt::runPass(), AST::IfStmt::runPass(), AST::FunctionCallExpr::runPass(), AST::VariableDefStmt::runPass(), AST::FunctionDef::runPass(), AST::WhileLoop::runPass(), AST::MethodCallExpr::runPass(), AST::MethodDef::runPass(), AST::VariableDefAssignStmt::runPass(), AST::ConstIntExpr::runPass(), and AST::VariableExpr::runPass().
void ASTPass::runOn (FunctionDef & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 19 of file ASTPass.cpp.
void ASTPass::runOn (MethodDef & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 22 of file ASTPass.cpp.
void ASTPass::runOn (Statement & expr) virtual
Definition at line 26 of file ASTPass.cpp.
void ASTPass::runOn (ReturnStmt & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 29 of file ASTPass.cpp.
void ASTPass::runOn (VariableDefStmt & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 32 of file ASTPass.cpp.
void ASTPass::runOn (VariableDefAssignStmt & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 35 of file ASTPass.cpp.
void ASTPass::runOn (Block & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 39 of file ASTPass.cpp.
void ASTPass::runOn (IfStmt & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 42 of file ASTPass.cpp.
void ASTPass::runOn (WhileLoop & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 45 of file ASTPass.cpp.
void ASTPass::runOn (TypeStmt & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 49 of file ASTPass.cpp.
void ASTPass::runOn (Expression & expr) virtual
Definition at line 53 of file ASTPass.cpp.
void ASTPass::runOn (FunctionCallExpr & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 56 of file ASTPass.cpp.
void ASTPass::runOn (MethodCallExpr & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 59 of file ASTPass.cpp.
void ASTPass::runOn (ConstIntExpr & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 62 of file ASTPass.cpp.
void ASTPass::runOn (VariableExpr & expr) virtual
Reimplemented in Passes::LLVMPass, Passes::PrintPass, Passes::VerifyOptimizePass, Passes::IdentifierPass, and Passes::TypePass.
Definition at line 65 of file ASTPass.cpp.
Member Data Documentation
AbstractSyntaxTree& AST::ASTPass::ast protected
Definition at line 17 of file ASTPass.hpp.
Referenced by Passes::LLVMPass::addScalarMethods(), Passes::LLVMPass::createLLVMTypes(), Passes::TypePass::run(), Passes::IdentifierPass::run(), Passes::VerifyOptimizePass::run(), Passes::PrintPass::run(), Passes::LLVMPass::run(), Passes::IdentifierPass::runOn(), and Passes::LLVMPass::runOn().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/ASTPass.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/ASTPass.cpp