AUC: Passes::VerifyOptimizePass Class Reference
Passes::VerifyOptimizePass Class Reference
Verify and optimize LLVM IR.
#include <VerifyOptimizePass.hpp>
Public Member Functions
VerifyOptimizePass (AST::AbstractSyntaxTree &ast)
virtual void run ()
virtual void runOn (AST::FunctionDef &)
virtual void runOn (AST::MethodDef &)
virtual void runOn (AST::ReturnStmt &)
virtual void runOn (AST::VariableDefStmt &)
virtual void runOn (AST::VariableDefAssignStmt &)
virtual void runOn (AST::Block &)
virtual void runOn (AST::IfStmt &)
virtual void runOn (AST::WhileLoop &)
virtual void runOn (AST::TypeStmt &)
virtual void runOn (AST::FunctionCallExpr &)
virtual void runOn (AST::MethodCallExpr &)
virtual void runOn (AST::ConstIntExpr &)
virtual void runOn (AST::VariableExpr &)
Public Member Functions inherited from AST::ASTPass
ASTPass (AbstractSyntaxTree &ast)
virtual void runOn (Declaration &)
virtual void runOn (Statement &)
virtual void runOn (Expression &)
Protected Attributes
std::unique_ptr< llvm::legacy::FunctionPassManager > functionPassMgr
std::unique_ptr< llvm::legacy::PassManager > modulePassMgr
Protected Attributes inherited from AST::ASTPass
AbstractSyntaxTree & ast
Detailed Description
Verify and optimize LLVM IR.
Definition at line 18 of file VerifyOptimizePass.hpp.
Constructor & Destructor Documentation
VerifyOptimizePass::VerifyOptimizePass (AST::AbstractSyntaxTree & ast)
Todo:
Add other pass managers: loop, basic block, call graph ?
Definition at line 25 of file VerifyOptimizePass.cpp.
References functionPassMgr, AST::AbstractSyntaxTree::getLLVMModule(), and modulePassMgr.
Member Function Documentation
void VerifyOptimizePass::run () virtual
Implements AST::ASTPass.
Definition at line 49 of file VerifyOptimizePass.cpp.
References AST::ASTPass::ast, functionPassMgr, AST::AbstractSyntaxTree::getDeclarations(), AST::AbstractSyntaxTree::getLLVMModule(), and modulePassMgr.
void VerifyOptimizePass::runOn (AST::FunctionDef & func) virtual
Reimplemented from AST::ASTPass.
Definition at line 59 of file VerifyOptimizePass.cpp.
References functionPassMgr, AST::Declaration::getBody(), AST::Declaration::getLLVMFunction(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), and AST::Block::runPass().
void VerifyOptimizePass::runOn (AST::MethodDef & func) virtual
Reimplemented from AST::ASTPass.
Definition at line 68 of file VerifyOptimizePass.cpp.
References functionPassMgr, AST::Declaration::getBody(), AST::Declaration::getLLVMFunction(), AST::MethodDef::getObjectTypeStmt(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), and AST::Block::runPass().
void VerifyOptimizePass::runOn (AST::ReturnStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 78 of file VerifyOptimizePass.cpp.
References AST::ReturnStmt::getValue().
void VerifyOptimizePass::runOn (AST::VariableDefStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 82 of file VerifyOptimizePass.cpp.
References AST::VariableDefStmt::getTypeStmt().
void VerifyOptimizePass::runOn (AST::VariableDefAssignStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 86 of file VerifyOptimizePass.cpp.
References AST::VariableDefStmt::getTypeStmt(), and AST::VariableDefAssignStmt::getValue().
void VerifyOptimizePass::runOn (AST::Block & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 91 of file VerifyOptimizePass.cpp.
References AST::Block::getStatements().
void VerifyOptimizePass::runOn (AST::IfStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 97 of file VerifyOptimizePass.cpp.
References AST::IfStmt::getBody(), AST::IfStmt::getCondition(), and AST::Block::runPass().
void VerifyOptimizePass::runOn (AST::WhileLoop & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 102 of file VerifyOptimizePass.cpp.
References AST::WhileLoop::getBody(), AST::WhileLoop::getCondition(), and AST::Block::runPass().
void VerifyOptimizePass::runOn (AST::TypeStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 107 of file VerifyOptimizePass.cpp.
void VerifyOptimizePass::runOn (AST::FunctionCallExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 110 of file VerifyOptimizePass.cpp.
References AST::FunctionCallExpr::getArgs().
void VerifyOptimizePass::runOn (AST::MethodCallExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 116 of file VerifyOptimizePass.cpp.
References AST::MethodCallExpr::getArgs(), and AST::MethodCallExpr::getObjectExpr().
void VerifyOptimizePass::runOn (AST::ConstIntExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 123 of file VerifyOptimizePass.cpp.
void VerifyOptimizePass::runOn (AST::VariableExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 126 of file VerifyOptimizePass.cpp.
Member Data Documentation
std::unique_ptr<llvm::legacy::FunctionPassManager> Passes::VerifyOptimizePass::functionPassMgr protected
Definition at line 21 of file VerifyOptimizePass.hpp.
Referenced by run(), runOn(), and VerifyOptimizePass().
std::unique_ptr<llvm::legacy::PassManager> Passes::VerifyOptimizePass::modulePassMgr protected
Definition at line 22 of file VerifyOptimizePass.hpp.
Referenced by run(), and VerifyOptimizePass().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/VerifyOptimizePass.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/VerifyOptimizePass.cpp