AUC: AST::BasicTypeStmt Class Reference
AST::BasicTypeStmt Class Reference
#include <TypeStmt.hpp>
Public Member Functions
BasicTypeStmt (std::string name, CodeLocation codeLocation)
virtual ~BasicTypeStmt ()
void runPass (ASTPass &pass)
std::string getName ()
Public Member Functions inherited from AST::TypeStmt
virtual ~TypeStmt ()
type::TypePtr getType ()
void setType (type::TypePtr type)
bool getIsReference ()
void setIsReference (bool isReference)
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
virtual ~ASTElement ()
CodeLocation getCodeLocation ()
Protected Attributes
std::string name
Protected Attributes inherited from AST::TypeStmt
type::TypePtr type
bool isReference
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Additional Inherited Members
Protected Member Functions inherited from AST::TypeStmt
TypeStmt (CodeLocation codeLocation)
Detailed Description
Definition at line 37 of file TypeStmt.hpp.
Constructor & Destructor Documentation
BasicTypeStmt()
BasicTypeStmt::BasicTypeStmt (std::string name, CodeLocation codeLocation)
Definition at line 34 of file TypeStmt.cpp.
~BasicTypeStmt()
virtual AST::BasicTypeStmt::~BasicTypeStmt () inline virtual
Definition at line 44 of file TypeStmt.hpp.
References AST::ASTElement::runPass().
Member Function Documentation
getName()
std::string BasicTypeStmt::getName ()
Definition at line 42 of file TypeStmt.cpp.
References name.
Referenced by Passes::IdentifierPass::runOn(), and Passes::OutputPass::runOn().
runPass()
void BasicTypeStmt::runPass (ASTPass & pass) virtual
Implements AST::ASTElement.
Definition at line 38 of file TypeStmt.cpp.
References AST::ASTPass::tryRunOn().
Member Data Documentation
name
std::string AST::BasicTypeStmt::name protected
Definition at line 40 of file TypeStmt.hpp.
Referenced by getName().
The documentation for this class was generated from the following files:
auc/AST/TypeStmt.hpp
auc/AST/TypeStmt.cpp