AUC: AST::CodeLocation Class Reference
AST::CodeLocation Class Reference
#include <CodeLocation.hpp>
Public Member Functions
CodeLocation (std::string filename, unsigned int line, unsigned int beginChar, unsigned int endChar)
virtual ~CodeLocation ()
std::string getFilename ()
unsigned int getLine ()
unsigned int getBeginChar ()
unsigned int getEndChar ()
std::string toString ()
Static Public Attributes
static CodeLocation none = {std::string(), 0, 0, 0}
Protected Attributes
std::string filename
unsigned int line
unsigned int beginChar
unsigned int endChar
Detailed Description
Definition at line 16 of file CodeLocation.hpp.
Constructor & Destructor Documentation
CodeLocation()
CodeLocation::CodeLocation (std::string filename, unsigned int line, unsigned int beginChar, unsigned int endChar)
Definition at line 14 of file CodeLocation.cpp.
~CodeLocation()
virtual AST::CodeLocation::~CodeLocation () inline virtual
Definition at line 26 of file CodeLocation.hpp.
References getBeginChar(), getEndChar(), getFilename(), getLine(), and toString().
Member Function Documentation
getBeginChar()
unsigned int CodeLocation::getBeginChar ()
Definition at line 27 of file CodeLocation.cpp.
References beginChar.
Referenced by ~CodeLocation().
getEndChar()
unsigned int CodeLocation::getEndChar ()
Definition at line 31 of file CodeLocation.cpp.
References endChar.
Referenced by ~CodeLocation().
getFilename()
std::string CodeLocation::getFilename ()
Definition at line 19 of file CodeLocation.cpp.
References filename.
Referenced by ~CodeLocation().
getLine()
unsigned int CodeLocation::getLine ()
Definition at line 23 of file CodeLocation.cpp.
References line.
Referenced by ~CodeLocation().
toString()
std::string CodeLocation::toString ()
Definition at line 35 of file CodeLocation.cpp.
References beginChar, endChar, filename, and line.
Referenced by AST::ASTPass::handleError(), and ~CodeLocation().
Member Data Documentation
beginChar
unsigned int AST::CodeLocation::beginChar protected
Definition at line 21 of file CodeLocation.hpp.
Referenced by getBeginChar(), and toString().
endChar
unsigned int AST::CodeLocation::endChar protected
Definition at line 21 of file CodeLocation.hpp.
Referenced by getEndChar(), and toString().
filename
std::string AST::CodeLocation::filename protected
Definition at line 19 of file CodeLocation.hpp.
Referenced by getFilename(), and toString().
line
unsigned int AST::CodeLocation::line protected
Definition at line 20 of file CodeLocation.hpp.
Referenced by getLine(), and toString().
none
CodeLocation CodeLocation::none = {std::string(), 0, 0, 0} static
Definition at line 34 of file CodeLocation.hpp.
The documentation for this class was generated from the following files:
auc/AST/CodeLocation.hpp
auc/AST/CodeLocation.cpp