AUC: AST::Block Class Reference
AST::Block Class Reference
#include <Blocks.hpp>
Public Member Functions
Block (Block *parentBlock, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)
StatementList & getStatements ()
void push_back (ASTPtr< Statement > statement)
ASTMap< VariableDefStmt * > & getVariables ()
Public Member Functions inherited from AST::Statement
Statement (Block *parentBlock, CodeLocation codeLocation)
Block * getParentBlock ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
StatementList statements
ASTMap< VariableDefStmt * > variables
Protected Attributes inherited from AST::Statement
Block * parentBlock
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 19 of file Blocks.hpp.
Constructor & Destructor Documentation
Block::Block (Block * parentBlock, CodeLocation codeLocation)
Todo:
Add a getName() method to Blocks, for context in error messages
Definition at line 12 of file Blocks.cpp.
Member Function Documentation
StatementList & Block::getStatements ()
Definition at line 22 of file Blocks.cpp.
References statements.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
ASTMap< VariableDefStmt * > & Block::getVariables ()
Definition at line 30 of file Blocks.cpp.
References variables.
Referenced by Passes::IdentifierPass::runOn().
void Block::push_back (ASTPtr< Statement > statement)
Definition at line 26 of file Blocks.cpp.
References statements.
void Block::runPass (ASTPass & pass) virtual
Implements AST::ASTElement.
Definition at line 18 of file Blocks.cpp.
References AST::ASTPass::runOn().
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
Member Data Documentation
StatementList AST::Block::statements protected
Definition at line 22 of file Blocks.hpp.
Referenced by getStatements(), and push_back().
ASTMap<VariableDefStmt*> AST::Block::variables protected
Definition at line 23 of file Blocks.hpp.
Referenced by getVariables().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Blocks.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Blocks.cpp