AUC: AST::MethodCallExpr Class Reference
AST::MethodCallExpr Class Reference
#include <Expressions.hpp>
Public Member Functions
MethodCallExpr (ASTPtr< Expression > tmpObjectExpr, std::string name, Block *parentBlock, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)
ASTPtr< Expression > getObjectExpr ()
std::string getName ()
std::string getMangledName ()
ASTList< Expression > & getArgs ()
MethodDef * getMethodDef ()
void setMethodDef (MethodDef *functionDef)
Public Member Functions inherited from AST::Expression
Expression (Block *parentBlock, CodeLocation codeLocation)
ASTPtr< Type > getType ()
void setType (ASTPtr< Type > type)
llvm::Value * getLLVMValue ()
void setLLVMValue (llvm::Value *llvmValue)
Public Member Functions inherited from AST::Statement
Statement (Block *parentBlock, CodeLocation codeLocation)
Block * getParentBlock ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
ASTPtr< Expression > objectExpr
std::string name
ASTList< Expression > args
MethodDef * methodDef
Protected Attributes inherited from AST::Expression
ASTPtr< Type > type
llvm::Value * llvmValue
Protected Attributes inherited from AST::Statement
Block * parentBlock
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 59 of file Expressions.hpp.
Constructor & Destructor Documentation
MethodCallExpr::MethodCallExpr (ASTPtr< Expression > tmpObjectExpr, std::string name, Block * parentBlock, CodeLocation codeLocation)
Definition at line 61 of file Expressions.cpp.
Member Function Documentation
ASTList< Expression > & MethodCallExpr::getArgs ()
Definition at line 83 of file Expressions.cpp.
References args.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
std::string MethodCallExpr::getMangledName ()
Definition at line 79 of file Expressions.cpp.
References name, and objectExpr.
Referenced by Passes::TypePass::runOn().
MethodDef * MethodCallExpr::getMethodDef ()
Definition at line 87 of file Expressions.cpp.
References methodDef.
Referenced by Passes::TypePass::runOn(), and Passes::LLVMPass::runOn().
std::string MethodCallExpr::getName ()
Definition at line 75 of file Expressions.cpp.
References name.
Referenced by Passes::PrintPass::runOn().
ASTPtr< Expression > MethodCallExpr::getObjectExpr ()
Definition at line 71 of file Expressions.cpp.
References objectExpr.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
void MethodCallExpr::runPass (ASTPass & pass) virtual
Implements AST::Expression.
Definition at line 67 of file Expressions.cpp.
References AST::ASTPass::runOn().
void MethodCallExpr::setMethodDef (MethodDef * functionDef)
Definition at line 91 of file Expressions.cpp.
References methodDef.
Referenced by Passes::TypePass::runOn().
Member Data Documentation
ASTList<Expression> AST::MethodCallExpr::args protected
Definition at line 64 of file Expressions.hpp.
Referenced by getArgs().
MethodDef* AST::MethodCallExpr::methodDef protected
Definition at line 65 of file Expressions.hpp.
Referenced by getMethodDef(), and setMethodDef().
std::string AST::MethodCallExpr::name protected
Definition at line 63 of file Expressions.hpp.
Referenced by getMangledName(), and getName().
ASTPtr<Expression> AST::MethodCallExpr::objectExpr protected
Definition at line 62 of file Expressions.hpp.
Referenced by getMangledName(), and getObjectExpr().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Expressions.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Expressions.cpp