AUC: AST::ReturnStmt Class Reference
AST::ReturnStmt Class Reference
#include <Statements.hpp>
Public Member Functions
ReturnStmt (ASTPtr< Expression > value, Block *parentBlock, CodeLocation codeLocation)
virtual void runPass (ASTPass &pass)
ASTPtr< Expression > getValue ()
Public Member Functions inherited from AST::Statement
Statement (Block *parentBlock, CodeLocation codeLocation)
Block * getParentBlock ()
Public Member Functions inherited from AST::ASTElement
ASTElement (CodeLocation codeLocation)
CodeLocation getCodeLocation ()
bool getExported ()
void setExported (bool exported)
Protected Attributes
ASTPtr< Expression > value
Protected Attributes inherited from AST::Statement
Block * parentBlock
Protected Attributes inherited from AST::ASTElement
CodeLocation codeLocation
Detailed Description
Definition at line 33 of file Statements.hpp.
Constructor & Destructor Documentation
ReturnStmt::ReturnStmt (ASTPtr< Expression > value, Block * parentBlock, CodeLocation codeLocation)
Definition at line 21 of file Statements.cpp.
Member Function Documentation
ASTPtr< Expression > ReturnStmt::getValue ()
Definition at line 30 of file Statements.cpp.
References value.
Referenced by Passes::TypePass::runOn(), Passes::IdentifierPass::runOn(), Passes::VerifyOptimizePass::runOn(), Passes::PrintPass::runOn(), and Passes::LLVMPass::runOn().
void ReturnStmt::runPass (ASTPass & pass) virtual
Implements AST::ASTElement.
Definition at line 26 of file Statements.cpp.
References AST::ASTPass::runOn().
Member Data Documentation
ASTPtr<Expression> AST::ReturnStmt::value protected
Definition at line 36 of file Statements.hpp.
Referenced by getValue().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Statements.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/AST/Statements.cpp