AUC: Passes::OutputPass Class Reference
Passes::OutputPass Class Reference
Print an AST as C code to an output stream.
#include <OutputPass.hpp>
Public Member Functions
OutputPass (AST::AbstractSyntaxTree &ast, std::ostream &stream)
virtual ~OutputPass ()
void run () override
void runOn (AST::FunctionDecl &) override
void runOn (AST::FunctionDef &) override
void runOn (AST::ReturnStmt &) override
void runOn (AST::VariableDefStmt &) override
void runOn (AST::VariableDefAssignStmt &) override
void runOn (AST::Block &) override
void runOn (AST::IfStmt &) override
void runOn (AST::WhileLoop &) override
void runOn (AST::BasicTypeStmt &) override
void runOn (AST::FunctionCallExpr &) override
void runOn (AST::ConstIntExpr &) override
void runOn (AST::VariableExpr &) override
Public Member Functions inherited from AST::ASTPass
ASTPass (AbstractSyntaxTree &ast)
virtual ~ASTPass ()
template<class T >
void tryRunOn (T &t)
virtual void runOn (Statement &)
virtual void runOn (TypeStmt &)
virtual void runOn (Expression &)
Additional Inherited Members
Protected Member Functions inherited from AST::ASTPass
void handleError (ASTElement &elem, const ASTError &err)
Protected Attributes inherited from AST::ASTPass
AbstractSyntaxTree & ast
Detailed Description
Print an AST as C code to an output stream.
Definition at line 18 of file OutputPass.hpp.
Constructor & Destructor Documentation
OutputPass()
OutputPass::OutputPass (AST::AbstractSyntaxTree & ast, std::ostream & stream)
Definition at line 19 of file OutputPass.cpp.
~OutputPass()
virtual Passes::OutputPass::~OutputPass () inline virtual
Definition at line 28 of file OutputPass.hpp.
References run(), and runOn().
Member Function Documentation
run()
void OutputPass::run () override virtual
Implements AST::ASTPass.
Definition at line 31 of file OutputPass.cpp.
References AST::ASTPass::ast, and AST::AbstractSyntaxTree::getDeclarations().
Referenced by ~OutputPass().
runOn() [1/12]
void OutputPass::runOn (AST::FunctionDecl & funcDecl) override virtual
Reimplemented from AST::ASTPass.
Definition at line 42 of file OutputPass.cpp.
Referenced by ~OutputPass().
runOn() [2/12]
void OutputPass::runOn (AST::FunctionDef & func) override virtual
Reimplemented from AST::ASTPass.
Definition at line 46 of file OutputPass.cpp.
References AST::FunctionDef::getBody(), AST::FunctionDef::getFunctionDecl(), and AST::FunctionDef::getName().
runOn() [3/12]
void OutputPass::runOn (AST::ReturnStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 61 of file OutputPass.cpp.
References AST::ReturnStmt::getValue().
runOn() [4/12]
void OutputPass::runOn (AST::VariableDefStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 66 of file OutputPass.cpp.
References AST::VariableDefStmt::getName(), and AST::VariableDefStmt::getTypeStmt().
runOn() [5/12]
void OutputPass::runOn (AST::VariableDefAssignStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 71 of file OutputPass.cpp.
References AST::VariableDefStmt::getName(), AST::VariableDefStmt::getTypeStmt(), and AST::VariableDefAssignStmt::getValue().
runOn() [6/12]
void OutputPass::runOn (AST::Block & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 77 of file OutputPass.cpp.
References AST::Block::getStatements().
runOn() [7/12]
void OutputPass::runOn (AST::IfStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 89 of file OutputPass.cpp.
References AST::IfStmt::getBody(), and AST::IfStmt::getCondition().
runOn() [8/12]
void OutputPass::runOn (AST::WhileLoop & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 96 of file OutputPass.cpp.
References AST::WhileLoop::getBody(), AST::WhileLoop::getCondition(), and AST::Block::runPass().
runOn() [9/12]
void OutputPass::runOn (AST::BasicTypeStmt & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 103 of file OutputPass.cpp.
References AST::TypeStmt::getIsReference(), and AST::BasicTypeStmt::getName().
runOn() [10/12]
void OutputPass::runOn (AST::FunctionCallExpr & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 110 of file OutputPass.cpp.
References AST::FunctionCallExpr::getArgs(), AST::FunctionCallExpr::getFunctionDecl(), AST::FunctionCallExpr::getName(), and AST::FunctionDecl::getParameters().
runOn() [11/12]
void OutputPass::runOn (AST::ConstIntExpr & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 138 of file OutputPass.cpp.
References AST::ConstIntExpr::getValueStr().
runOn() [12/12]
void OutputPass::runOn (AST::VariableExpr & stmt) override virtual
Reimplemented from AST::ASTPass.
Definition at line 142 of file OutputPass.cpp.
References AST::VariableExpr::getName().
The documentation for this class was generated from the following files:
auc/Passes/OutputPass.hpp
auc/Passes/OutputPass.cpp