AUC: Passes::TypePass Class Reference
Passes::TypePass Class Reference
Resolve and check types of expressions.
#include <TypePass.hpp>
Public Member Functions
TypePass (AST::AbstractSyntaxTree &ast)
virtual void run ()
virtual void runOn (AST::FunctionDef &)
virtual void runOn (AST::MethodDef &)
virtual void runOn (AST::ReturnStmt &)
virtual void runOn (AST::VariableDefStmt &)
virtual void runOn (AST::VariableDefAssignStmt &)
virtual void runOn (AST::Block &)
virtual void runOn (AST::IfStmt &)
virtual void runOn (AST::WhileLoop &)
virtual void runOn (AST::TypeStmt &)
virtual void runOn (AST::FunctionCallExpr &)
virtual void runOn (AST::MethodCallExpr &)
virtual void runOn (AST::ConstIntExpr &)
virtual void runOn (AST::VariableExpr &)
Public Member Functions inherited from AST::ASTPass
ASTPass (AbstractSyntaxTree &ast)
virtual void runOn (Declaration &)
virtual void runOn (Statement &)
virtual void runOn (Expression &)
Additional Inherited Members
Protected Attributes inherited from AST::ASTPass
AbstractSyntaxTree & ast
Detailed Description
Resolve and check types of expressions.
Definition at line 16 of file TypePass.hpp.
Constructor & Destructor Documentation
TypePass::TypePass (AST::AbstractSyntaxTree & ast)
Definition at line 21 of file TypePass.cpp.
Member Function Documentation
void TypePass::run () virtual
Implements AST::ASTPass.
Definition at line 25 of file TypePass.cpp.
References AST::ASTPass::ast, and AST::AbstractSyntaxTree::getDeclarations().
void TypePass::runOn (AST::FunctionDef & func) virtual
Reimplemented from AST::ASTPass.
Definition at line 31 of file TypePass.cpp.
References AST::Declaration::getBody(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), and AST::Block::runPass().
void TypePass::runOn (AST::MethodDef & func) virtual
Reimplemented from AST::ASTPass.
Definition at line 39 of file TypePass.cpp.
References AST::Declaration::getBody(), AST::MethodDef::getObjectTypeStmt(), AST::Declaration::getParameters(), AST::Declaration::getReturnTypeStmt(), and AST::Block::runPass().
void TypePass::runOn (AST::ReturnStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 48 of file TypePass.cpp.
References AST::ReturnStmt::getValue().
void TypePass::runOn (AST::VariableDefStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 52 of file TypePass.cpp.
References AST::VariableDefStmt::getTypeStmt().
void TypePass::runOn (AST::VariableDefAssignStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 56 of file TypePass.cpp.
References AST::VariableDefStmt::getTypeStmt(), and AST::VariableDefAssignStmt::getValue().
void TypePass::runOn (AST::Block & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 61 of file TypePass.cpp.
References AST::Block::getStatements().
void TypePass::runOn (AST::IfStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 67 of file TypePass.cpp.
References AST::IfStmt::getBody(), AST::IfStmt::getCondition(), and AST::Block::runPass().
void TypePass::runOn (AST::WhileLoop & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 72 of file TypePass.cpp.
References AST::WhileLoop::getBody(), AST::WhileLoop::getCondition(), and AST::Block::runPass().
void TypePass::runOn (AST::TypeStmt & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 77 of file TypePass.cpp.
void TypePass::runOn (AST::FunctionCallExpr & stmt) virtual
Check argument types
Todo:
Add search for implicit cast method
Todo:
Merge common code of FunctionCallExpr and MethodCallExpr handling
Reimplemented from AST::ASTPass.
Definition at line 80 of file TypePass.cpp.
References AST::FunctionCallExpr::getArgs(), AST::FunctionCallExpr::getFunctionDef(), AST::FunctionCallExpr::getName(), and AST::Declaration::getParameters().
void TypePass::runOn (AST::MethodCallExpr & stmt) virtual
Resolve method identifier (type of stmt.getObjectExpr() is resolved now)
Check argument types
Todo:
Add search for implicit cast method
Reimplemented from AST::ASTPass.
Definition at line 99 of file TypePass.cpp.
References AST::MethodCallExpr::getArgs(), AST::MethodCallExpr::getMangledName(), AST::MethodCallExpr::getMethodDef(), AST::MethodCallExpr::getObjectExpr(), AST::Declaration::getParameters(), and AST::MethodCallExpr::setMethodDef().
void TypePass::runOn (AST::ConstIntExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 130 of file TypePass.cpp.
References AST::ConstIntExpr::getTypeStmt(), and AST::Expression::setType().
void TypePass::runOn (AST::VariableExpr & stmt) virtual
Reimplemented from AST::ASTPass.
Definition at line 135 of file TypePass.cpp.
References AST::VariableDefStmt::getTypeStmt(), AST::VariableExpr::getVariableDefStmt(), and AST::Expression::setType().
The documentation for this class was generated from the following files:
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/TypePass.hpp
/home/ladmin/SafeBox/Software/aurum-lang/src/auc/Passes/TypePass.cpp